[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/healthz"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/version"
  to = "/.netlify/functions/server"
  status = 200
